module.exports={
    userType:{
        customer:"Customer",
        engineer:"Engineer",
        admin:"Admin"
    },
    userStatus:{
        approved:"Approved",
        pending:"Pending",
        blocked:"Blocked"
    }
}